name: Deploy
on:
  workflow_dispatch: {}
  push:
    branches:
      - main
env:
  AWS_REGION: ap-southeast-2
  USERPOOL_ID: ${{ vars.USERPOOL_ID }}
jobs:
  deploy-dev:
    environment: Dev
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - run: npm ci
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.IAM_ROLE }}
          aws-region: ap-southeast-2
      - run: npx cdk deploy Dev-AwsInfraStack --auto-approve --require-approval never

  deploy-staging:
    needs: deploy-dev
    environment:
      name: Staging
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - run: npm ci
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.IAM_ROLE }}
          aws-region: ap-southeast-2
      - run: npx cdk deploy Staging-AwsInfraStack --auto-approve --require-approval never

  deploy-prod:
    needs: deploy-staging
    environment:
      name: Prod
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - run: npm ci
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.IAM_ROLE }}
          aws-region: ap-southeast-2
      - run: npx cdk deploy Prod-AwsInfraStack --auto-approve --require-approval never
